// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dermaai/AnalysisResult.tsx": () => import("../components/mockups/dermaai/AnalysisResult.tsx"),
  "./components/mockups/dermaai/Dashboard.tsx": () => import("../components/mockups/dermaai/Dashboard.tsx"),
  "./components/mockups/dermaai/Landing.tsx": () => import("../components/mockups/dermaai/Landing.tsx"),
  "./components/mockups/dermaai/Login.tsx": () => import("../components/mockups/dermaai/Login.tsx"),
  "./components/mockups/dermaai/Questionnaire.tsx": () => import("../components/mockups/dermaai/Questionnaire.tsx"),
  "./components/mockups/dermaai/Recommendations.tsx": () => import("../components/mockups/dermaai/Recommendations.tsx"),
  "./components/mockups/dermaai/Signup.tsx": () => import("../components/mockups/dermaai/Signup.tsx"),
  "./components/mockups/dermaai/SkinScan.tsx": () => import("../components/mockups/dermaai/SkinScan.tsx")
};
